### ISSUE TITLE
Storing the correct model

### ISSUE THREAD

**Issue by IssamT** [JuliaOpt/MathOptInterfaceUtilities.jl#2]
Shouldn't we add copying in this function?
This is related to the issue JuliaOpt/MathOptInterface#67

```julia
function _addconstraint!{F, S}(constrs::Vector{Tuple{CR{F, S}, F, S}}, cr::CR, f::F, s::S)
    push!(constrs, (cr, f, s))
    length(constrs)
end

**Comment by blegat** [comment]
Good question. I would say that if we use the performance hints then yes we should copy if the performance hint has not been given. Otherwise, no otherwise it will trigger copies for JuMP which [we do not want](https://github.com/JuliaOpt/MathOptInterface.jl/pull/67#issuecomment-316678274).

**Comment by IssamT** [comment]
How does this relate to #32 ? I think copying will be only done for what is stored in the standalone instance while the arguments used to call the wrapper functions shouldn't be used by the wrapper after the function call.

**Comment by blegat** [comment]
This is related to MOI.Utilities.Model which now contains the copy. @IssamT reopen in MOI.jl if there is still something to discuss
