### ISSUE TITLE
Removing a variable

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/MathOptInterfaceUtilities.jl#3]
When remove a variable, should we update every function to remove the variable ?

**Comment by mlubin** [comment]
Well you can't return dead variables when the user asks for the function afterwards, but you can defer the updating if you prefer.

**Comment by mlubin** [comment]
Removing variables is supported now. Any reason to leave the issue open?

**Comment by blegat** [comment]
No it should be closed
