### ISSUE TITLE
[RFC] Functions and Set bridges

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/MathOptInterfaceUtilities.jl#30]
Solvers often support a specific set of (function, set) constraints but other constraint can be transformed into these pairs.
Therefore, different wrappers usually need to develop the same transformation without sharing code. Having these transformation in addition to the rest makes the wrapper code significantly more complicated (even more if it want to return ListOfConstraints, ... accurately).
Sometimes, we would also like to add the support of a (function, set) pair to a solver since we know to transform them into other constraints but we do not want to patch every solver since it would take time and our new constraint may be application specific and not of broad interest.

I think that these uses cases could be easy to solve if the following macro existed:
```julia
@bridge Name SomeFunction SomeSet SomeBridge
```
The macro would create an instance bridge `Name <: AbstractSolverInstance` such that `Name(instance)` creates an instance that supports all constraints supported by `instance` plus `(SomeFunction, SomeSet)`.
The macro would basically create
```julia
struct Name{InstanceType}
    instance::InstanceType
    bridges::Vector{SomeBridge}
end
```

I have already created some bridges [in SDOI](https://github.com/JuliaOpt/SemidefiniteOptInterface.jl/blob/master/src/setbridges.jl) and it works quite well. The macro does not exist yet though so I had to complicate the wrapper interface to add the `bridges::Vector{SomeBridge}` inside the wrapper structure, ...
Once the macro is created, this would allow to make SDOI a lot simpler.

Some examples of useful bridges:
* `AbstractVectorFunction` in `PositiveSemidefiniteConeSquare`, see https://github.com/JuliaOpt/JuMP.jl/pull/1125
* `AbstractVectorFunction` in `LogDetCone`, i.e. `log det(X) <= t`
* `AbstractVectorFunction` in `DetRootnCone`, i.e. `det(X) <= t^n`

**Comment by mlubin** [comment]
I think the big challenge here is not just the forward mapping but also correctly mapping back attributes like duals. It will probably take some experimentation to get things right, so go for it.

**Comment by blegat** [comment]
In fact, DCP could be implemented as a constraint bridge.

Le sam. 18 nov. 2017 à 16:18, Miles Lubin <notifications@github.com> a
écrit :
