### ISSUE TITLE
Redirecting problem modification

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/MathOptInterfaceUtilities.jl#34]
Currently, the same code is written [in ECOS](https://github.com/JuliaOpt/MathOptInterfaceECOS.jl/blob/master/src/data.jl), [in SCS](https://github.com/JuliaOpt/MathOptInterfaceSCS.jl/blob/master/src/data.jl), [in SDOI](https://github.com/JuliaOpt/SemidefiniteOptInterface.jl/blob/master/src/data.jl) and [in MOIU/bridge.jl](https://github.com/JuliaOpt/MathOptInterfaceUtilities.jl/blob/4b0c0470e8615669b8e225e5f24f4b857e6608db/src/bridge.jl#L47-L104).

It would be good to avoid having this chunk of code copy pasted everywhere. I can see two solution, vote for your preferred one:

- Have an abstract type defined in MOIU like `AbstractSolverInstanceWithInstance` described in MOIU and have this code for this abstract type only once here :+1: 
- Have a macro like `@redirectinstancemodification solverinstancetype instancefield` that returns this code that is duplicated :heart: 
- None of them, I like copy paste :-1: 

This seems related to InstanceManager (see #32 ) so we might have code shared between the two.

**Comment by ccoffrin** [comment]
In the case of the first option would it be something like this, `ECOSSolverInstance <: AbstractSolverInstanceWithInstance`?

**Comment by blegat** [comment]
Yes exactly, and `AbstractSolverInstanceWithInstance <: AbstractSolverInstance`

**Comment by joaquimg** [comment]
In LQOI I did a macro to add the mandatory fields of the `LinQuadSolverInstance` (which should be renamed to `AbstractLinQuadSolverInstance` to follow MOI´s convention). I like options 1 and 2 more than 3.

**Comment by ccoffrin** [comment]
I am also in favor of 1+2.  I recently learned about this package which can be used to enforce fields in subtypes.  

https://github.com/tbreloff/ConcreteAbstractions.jl

Maybe be useful here?

**Comment by odow** [comment]
I prefer the copy paste. Using macros for everything just adds to the complexity.

**Comment by joaquimg** [comment]
I agree that code clarity is extremely important. But I if the macros are simple or use maintained packages, they would be a good solution.

**Comment by ccoffrin** [comment]
I generally try to avoid macros, but I find some times they are unavoidable.  Especially when the desired feature is not present in Julia.

**Comment by mlubin** [comment]
Something seems a bit off if we're going to have JuMP sit on top of an InstanceManager which sits on top of (for example) MathOptInterfaceECOS which has its own internal StandaloneInstance and another copy loaded into the ECOS API. That's three copies of the problem data. That *could* be avoided by attaching JuMP directly to the MOIECOS instance, but this would require users to be aware of the implementation. Can we figure out a way for the InstanceManager and MOIECOS to share data, for example?

**Comment by blegat** [comment]
It can make it default for JuMP that if the solver says that it can handle all problem modifications then when the solver is attached, JuMP gives it all the problems and then drops its internal instance. When the solver is detached, JuMP can ask the solver to spit the instance back.
This is the job of the instance manager. By default, it should do the most efficient thing that still allows the user to do everything. If for a solver, the user can be allowed to do everything without JuMP storing any copy then it should drop the copy.

**Comment by odow** [comment]
> By default, it should do the most efficient thing that still allows the user to do everything. If for a solver, the user can be allowed to do everything without JuMP storing any copy then it should drop the copy.

JuMP is just a nice interface for MOI. I'm going to stick with my [comment](https://github.com/JuliaOpt/MathOptInterfaceUtilities.jl/issues/32#issuecomment-346688634). JuMP should support both modes (direct to solverinstance, and managed instance), but the user should explicitly choose. Getting into a situation where JuMP decides "I'm probably okay to drop my copy of the data" seems worrying.

In my view,  if ECOS doesn't support adding variables and constraints one-by-one, then MathOptInterfaceECOS should not support that. Therefore, the only way to use it is through a managed instance. Maybe MathOptInterfaceECOS should just define
```julia
struct ECOSInstance
    ptr
    variables::Vector{VariableReference} # mapping between column and variable reference
    ... other stuff ...
end
function MOI.copy!(dest::ECOSInstance, src::AbstractInstance)
    ... stuff to get information out of src
    dest.ptr = ECOS.setup( ... )
end
```
Then the standalone instance can support problem modification and all that jazz. Workflow looks something like
```julia
instance = StandaloneInstance()
x = MOI.addvariables(m, 10)
... other moi stuff ...
ecos = ECOSInstance()
MOI.copy!(ecos, instance)
MOI.optimize!(ecos)
MOI.get(ecos, MOI.VariablePrimal(), x)
```

**Comment by mlubin** [comment]
@odow, I agree, and I like the proposed workflow. We need to rethink some concepts now that we're imagining an instance manager as a first-class MOI object. It's okay to have a solver instance that supports `copy!` but not `addconstraint!`. We also need a solution to https://github.com/JuliaOpt/MathOptInterface.jl/issues/163 to make it easy to use references between the manager and the solver instance.

**Comment by blegat** [comment]
That's an interesting idea. But it might complicate the bridging. SCS, ... will need to do the bridging inside copy! in a different way than Mosek.

**Comment by blegat** [comment]
I can see two possibilities:
1) We implement an alternative of `copy!` called something like `become!` where the instance becomes the previous instance. Which means that it uses the exact same constraint references. For solvers that have troubles doing this, it can simply use a `Dict` to map the references. For solvers like SCS, ECOS, SDOI solvers, ... they simply use the instance as their `data` field if it is an MOIU instance. Otherwise (if they are given a Mosek instance for example), they create an MOIU instance, ask it to become the Mosek instance and then use this in their `data` field. The InstanceManager, always stores exactly one instance (not an MOIU instance and a solver instance). This kind of assumes that all solvers support the full MOI interface (which is currently the case anyway). When something new is attached, it becomes the previews instance (it eats it !).
2) We remove the `data` field from SCS, ECOS, SDOI solvers, ... and the InstanceManager is responsible for storing the data for them. It has two fields, one with an MOIU instance and one with the solver. When a new solver is attached, it needs to have some parametrized synchronising if the solver supports modifications directly like LP solvers and Mosek, e.g. do I drop the MOIU instance. Since we may change solver, drop the MOIU instance, ... the constraint reference that the user hold may not at all be the correct constraint reference. A simple solution to that would be to have a mapping in a dictionary inside the InstanceManager. For SCS, ECOS, SDOI solvers, ..., it will only load the instance at `optimize!`.

The advantage of 1) is that it still allows the user to use solver instances without instance manager is a solver independent way and that it does not need to care too much about parametrizing the InstanceManager. The disadvantage of 1) is that it is more work for the solver wrappers as they need to implement `become!`, it also forces them to implement MOI in full.
One disadvantage of 2) is that we maybe need to update MOI to add a way for the InstanceManager to know whether the solver wants all data at once or not. It might be a worthwhile change but in the future, most solvers may support loading the data constraint by constraint, ...

What do you think ?

**Comment by mlubin** [comment]
> SCS, ... will need to do the bridging inside copy! in a different way than Mosek.

That seems pretty natural given that SCS and Mosek are very different. What if the InstanceManager did the bridging? One issue with the current setup for bridges is that the solver MOI interfaces have to explicitly [opt into](https://github.com/JuliaOpt/MathOptInterfaceSCS.jl/blob/c287d22cbae30f6d378da9888d22934e5296602a/src/MathOptInterfaceSCS.jl#L31)  the sets they support, which isn't friendly to users who don't have commit access to the solver wrappers.

> 1. We implement an alternative of `copy!` called something like `become!` where the instance becomes the previous instance. 

I'd call this `move!`. It would move the data from the given instance into a new concrete instance that supports the required function-set pairs, then clear the data in the given instance. Sometimes creating a new instance and sometimes using the given instance seems overly complex. There's also the question of surprising consequences if someone keeps a reference to the given instance.

> 2. We remove the `data` field from SCS, ECOS, SDOI solvers, ... and the InstanceManager is responsible for storing the data for them. It has two fields, one with an MOIU instance and one with the solver. When a new solver is attached, it needs to have some parametrized synchronising if the solver supports modifications directly like LP solvers and Mosek, e.g. do I drop the MOIU instance.

No, it should be an explicit choice by the user to drop the MOIU instance or not.

> For SCS, ECOS, SDOI solvers, ..., it will only load the instance at `optimize!`.

That's not quite right. ECOS and SCS support changing the objective and RHS vectors efficiently.

> Since we may change solver, drop the MOIU instance, ... the constraint reference that the user hold may not at all be the correct constraint reference. 

Why not make it a requirement that references remain valid after a `copy!`?

**Comment by mlubin** [comment]
Here's a proposal:

- Solver wrappers should *not* need to have internal standalone instances. They translate the problem directly to the solver's API. Let the solver API store/own the data, and the wrapper should store the necessary maps. (Minor exception: extreme cases like ECOS where the solver assumes that the user manages the memory for the input data.)
   - If the solver API doesn't support adding constraints, then don't implement `addconstraint!`.
   - If the solver API doesn't support querying the constraint coefficients, then don't support the `ConstraintFunction` attribute.

- Solver wrappers should implement at least `copy!` (analogous to MPB's `loadproblem!`). `copy!` returns a dictionary-like object that can be used to translate references (https://github.com/JuliaOpt/MathOptInterface.jl/issues/163#issuecomment-348375183).

- We have a new MOI object called an `InstanceManager` (name to be bikeshedded). The instance manger does everything you'd want JuMP to do, but without nice syntax. An instance manager has an internal standalone instance. It can attach to a solver instance using `copy!`. The instance manager is responsible for:
   - keeping the attached solver instance in sync with the internal standalone instance (including dealing with references)
   - bridges

- Users must explicitly specify to the instance manager which bridges they want to enable. As a result, you can use any bridge with any applicable solver, no need for the solver to opt in.

- The instance manager API is similar to the MOI solver instance API, but with some slight additions (i.e., for attaching and detaching) and modifications (to distinguish between attributes that pass through to the attached solver and attributes that apply to the standalone instance).

- JuMP can *either* use an instance manager or directly attach to an MOI solver instance ("no training wheels" mode). Clearly, JuMP will only be able to attach to solver instances that support `addconstraint!`, but these are the ones that you would care to use this feature with anyway. (Note: bulk additions of constraints using `copy!` could be faster than calling `addconstraint!`, so it may not always be a performance win. It will be a memory win, however.)

- Perhaps, callbacks will be easier to support only in the "no training wheels" mode. Callbacks don't compose naturally with bridges. The solvers that support callbacks also have full APIs that support `addconstraint!`.

This will mean a big change for how we test solvers. I think pressure to pass all the existing tests has pushed the solver wrappers to unnecessarily implement the full MOI API. I would see the current tests passing for the instance manager but not most solvers. Then again, we should not test the instance manager with a barrage of problems... we should test its API and that it attaches to solver instances correctly. Feels like we're repeating the testing discussion for JuMP.

Thoughts?

**Comment by blegat** [comment]
> One issue with the current setup for bridges is that the solver MOI interfaces have to explicitly opt into the sets they support, which isn't friendly to users who don't have commit access to the solver wrappers.

No the user can also do `instance = SomeOtherBridge{Float64}(MosekInstance())` outside of the SCS package and it works just as well.
One simple way to apply bridges to instance manager is to put the bridges in top like
`LogDetBridge{Float64}(InstanceManager(instance, solver))`

**Comment by mlubin** [comment]
> No the user can also do instance = SomeOtherBridge{Float64}(MosekInstance()) outside of the SCS package and it works just as well.

It's confusing that some bridges would be automatically set up and some not.

> One simple way to apply bridges to instance manager is to put the bridges in top like
`LogDetBridge{Float64}(InstanceManager(instance, solver))`

Works for me.

**Comment by blegat** [comment]
> It's confusing that some bridges would be automatically set up and some not.

Bridges are currently applied directly in the wrapper so that the user does not have to care about it for basic cones but it might be better if JuMP detects which bridges are needed.

**Comment by mlubin** [comment]
> Bridges are currently applied directly in the wrapper

To be more precise, they're applied by you to cover the cones that you mostly care about. If the user cases about the same cones as @blegat, then they're in good shape, otherwise they'll end up a bit confused.

**Comment by mlubin** [comment]
I think this is resolved now, or at least we've made substantial progress.
