### ISSUE TITLE
unsafe dictionary keys

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/MathOptInterfaceUtilities.jl#44]
Following up on the discussion at https://github.com/JuliaOpt/MathOptInterfaceUtilities.jl/commit/f8667f2d450202b6cf215e7fccafd625ec756eaf. It should be seen as an unsafe operation to store an `Int64` when a more specific index type could be used instead. It's unsafe because it disregards type information and easily leads to unintended behavior like https://github.com/JuliaOpt/MathOptInterfaceUtilities.jl/issues/41. Performance is not a good reason to do unsafe things unless you have benchmarks to show otherwise. 

See the following benchmark:
```julia
using BenchmarkTools

struct Index{T}
    value::Int
end

function f1()
    d = Dict{Index, Float64}()
    for k in 1:1000
        d[Index{String}(k)] = 2.0*k
    end
    s = 0.0
    for k in 1:1000
        s += d[Index{String}(k)]
    end
    return s
end

function f2()
    d = Dict{Index{String}, Float64}()
    for k in 1:1000
        d[Index{String}(k)] = 2.0*k
    end
    s = 0.0
    for k in 1:1000
        s += d[Index{String}(k)]
    end
    return s
end

@btime f1()
@btime f2()
```
On a recent Julia 0.7 I get:
```
  159.473 μs (3018 allocations: 139.22 KiB) # f1
  141.097 μs (2926 allocations: 137.78 KiB) # f2
```

I don't see this as a significant performance hit.

**Comment by blegat** [comment]
That's interesting, I guess there is no performance bottleneck because it is the key that is not fully typed and not the value and the key is given by the user.

**Comment by mlubin** [comment]
Is this resolved now?
