### ISSUE TITLE
How does MOIU fit into the solvers?

### ISSUE THREAD

**Issue by odow** [JuliaOpt/MathOptInterfaceUtilities.jl#5]
So I'm confused about what data structure solvers should use to store their models. Am I meant to be using MOIU? Because JuMP is using it. So it doesn't seem like there should be three copies of the model.

There is also things like: https://github.com/JuliaOpt/MathOptInterfaceUtilities.jl/blob/master/src/instance.jl#L47
But it's not apparent to me that all solvers will want to increment their variable references like that (maybe I support normal variables, and some other kind of variables, and I want to make normal variables even numbered, and weird variables odd numbered so I have a `mod` operation to check rather than some lookup).

I almost think we should write the solvers a few different ways. Check which ideas work well. Then consider abstracting into some instance type.

**Comment by blegat** [comment]
The `Instance` type is not meant to be used by solver wrappers. As you say, the solver will have very different ways to implement MOI. `Instance` is only meant to by used by JuMP and SOI.

**Comment by odow** [comment]
Okay, I just got confused because "Solver Wrapper" to me means CPLEX etc.

**Comment by joaquimg** [comment]
Thats better I was getting confused also...

**Comment by blegat** [comment]
There will be the sets and functions bridges that will be useful to the solvers, e.g. quadratic function to SOC

**Comment by mlubin** [comment]
The organization is still up for discussion. We'll have to see what utilities are worth abstracting across solver wrappers.

**Comment by mlubin** [comment]
Can we consider this resolved with https://github.com/JuliaOpt/MathOptInterface.jl/pull/131 and https://github.com/JuliaOpt/LinQuadOptInterface.jl?

**Comment by joaquimg** [comment]
I think so
