### ISSUE TITLE
Update for copy! changes

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/MathOptInterfaceUtilities.jl#53]
https://github.com/JuliaOpt/MathOptInterface.jl/pull/190
https://github.com/JuliaOpt/MathOptInterfaceTests.jl/pull/37
May also want to wait for https://github.com/JuliaOpt/MathOptInterface.jl/pull/189#issuecomment-355758664

**Comment by mlubin** [comment]
@blegat is this done?

**Comment by blegat** [comment]
Yep, should be :)
