### ISSUE TITLE
Instance should support arbitrary attributes

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/MathOptInterfaceUtilities.jl#61]
In the instance manager, attributes are typically set in both the solver instance and the standalone instance. In automatic mode, they *must* be set in both, because the solver could be emptied at any time. This means that the standalone instance needs to support all the attributes that the user might want to set on the solver instance. We don't know ahead of time which attributes these are going to be, and they might not be defined in MOI. This points in the direction of having an instance that supports arbitrary attributes, otherwise the usability of the instance manager (and therefore JuMP) is going to be severely restricted.

If we do this, we should consider addressing https://github.com/JuliaOpt/MathOptInterface.jl/issues/31 so that the container type to store attribute values can be inferred from the attribute itself. The performance considerations are closely related to the discussion in https://github.com/JuliaOpt/JuMP.jl/issues/1152.

**Comment by blegat** [comment]
I think the approach of https://github.com/JuliaOpt/JuMP.jl/issues/1152 fits perfectly for attributes.
We could have a `Dict{Tuple{AbstractVariableAttribute, VariableIndex}, Any}` or `Dict{AbstractVariableAttribute, Dict{VariableIndex}}`.
The second approach might be better but it needs https://github.com/JuliaOpt/MathOptInterface.jl/issues/31 to be resolved first.
We may start with the first one for this reason.

**Comment by mlubin** [comment]
Closing in favor of https://github.com/JuliaOpt/MathOptInterface.jl/issues/285
