### ISSUE TITLE
Problem Matrix for MILP 

### ISSUE THREAD

**Issue by IssamT** [JuliaOpt/MathOptInterfaceUtilities.jl#8]
MOI methods that add constraints using affine functions build the problem matrix on the side of MILP solvers. The datastructure and the interface to those solvers has a generic part (everything except the compression type used by the matrix).

Should we have this in MOIU ?

related to #5 and JuliaOpt/Clp.jl#21

**Comment by IssamT** [comment]
MILP solver wrappers have many things in common: the way they deal with bound constraints, the implication of this on constraint references etc...

I will try to deccorelate all this within the CLP MOI wrapper, and we can get back later on to this issue to see if it's generic enough to be moved to MOIU.

**Comment by blegat** [comment]
I am not sure to understand what you mean, could you give an example ?

**Comment by IssamT** [comment]
An example would be the way wrappers are implemented now with MPB. They create the matrix before passing it fully to the solver. But it seems we are going more on the direction of having MOI as close as possible to solver APIs without preprocessing or caching. We are discussing it here JuliaOpt/Clp.jl#21

**Comment by mlubin** [comment]
Can this issue be closed?

**Comment by IssamT** [comment]
I had a look at `LinQuadOptInterface.jl` and I think it answers my question about code duplication between MILP wrappers. Please correct me @joaquimg if I am wrong. After I run some benchmarks using the current MOI CLP wrapper I should try to replace most of it using `LinQuadOptInterface.jl`. 

The only remaining part of my question is "the storing" in order to answer user queries but this should be answered by #32, so yes I think this issue can be closed.

**Comment by joaquimg** [comment]
About using `LinQuadOptInterface.jl` that is totally up to the wrapper writer. If you consider it a simple task it might worth the effort. So that we can join forces later on for optimizing data structures, performance critical points etc.
