### ISSUE TITLE
Attributes canget too strict

### ISSUE THREAD

**Issue by tkoolen** [JuliaOpt/MathOptInterfaceUtilities.jl#87]
In

https://github.com/JuliaOpt/MathOptInterfaceUtilities.jl/blob/c5b5c4bcae650a141101fb1e16d459c84e582bb9/src/instancemanager.jl#L359-L364

`typeof(index)` is used for `canget`, even though a concrete index is available. That seems too strict. It may be the case that you can get an attribute for certain indices, but not all.

**Comment by mlubin** [comment]
This was discussed at https://github.com/JuliaOpt/MathOptInterface.jl/issues/191. Allowing the possibility for an attribute not to be available for a subset of indices forces inefficiencies in `copy!` (e.g., we can't query for all values at the same time). It also adds an extra level of state (and hence complexity) that I don't see a compelling need for.

**Comment by mlubin** [comment]
Also using indices instead of types in the code block referenced above would mean that for the same attribute, the instancemanager could sometimes return the value from the solver and sometimes from the instance. That's just confusing.

**Comment by tkoolen** [comment]
Ah, my mistake. I thought there was also a `canget` method with `::VariableIndex` argument, in addition to the `::Type{VariableIndex}` version, but I must have misread the MOI docs. I mistakenly implemented the former instead of the latter.
