### ISSUE TITLE
Instance can't store VariablePrimalStart

### ISSUE THREAD

**Issue by tkoolen** [JuliaOpt/MathOptInterfaceUtilities.jl#88]
Probably falls under https://github.com/JuliaOpt/MathOptInterfaceUtilities.jl/issues/61, feel free to close if you think it does.

**Comment by mlubin** [comment]
Yes, this is known: https://github.com/JuliaOpt/JuMP.jl/blob/1cc5e7fba68dc5c4ae6d138998e1d61a5a6ac9dc/src/macros.jl#L901

**Comment by blegat** [comment]
We should decide whether this could be handled by https://github.com/JuliaOpt/MathOptInterfaceUtilities.jl/issues/84 or whether the additional lookup in `varattr` and the fact that the return type may not be properly inferred is a performance issue and we should rather implement it directly into the MOIU instance

**Comment by mlubin** [comment]
Closing in favor of https://github.com/JuliaOpt/MathOptInterface.jl/issues/285
